Add a command to invalidate the LDAP cache
owncloud/user_ldap pull request #670
Opened 2021-07-22 11:18 UTC by jvillafanez

Link to https://github.com/owncloud/enterprise/issues/4533

The command will remove ALL the cache entries associated to the LDAP app.

2021-07-22 14:07 UTC, mmattel commented
Docs relevant, pls file an issue when close to merge.
@EParzefall fyi

2021-07-23 12:37 UTC, jvillafanez commented
There are no tests for any of the commands nor the `User_Proxy` nor `Group_Proxy`

2021-07-26 07:21 UTC, JanAckermann commented on lib/Command/InvalidateCache.php
> + * @license AGPL-3.0
You should be here

2021-07-26 07:27 UTC, JanAckermann approved these changes
Code LGTM, thinking about some more tests, at least a command unit test

2021-07-26 07:28 UTC, JanAckermann commented
Restarting tests

2021-07-27 13:13 UTC, JammingBen requested changes
Tiny thing, rest LGTM

2021-07-27 13:13 UTC, JammingBen commented on lib/Command/InvalidateCache.php
> +	private $cache;
These vars can be removed because unused I believe. Also some imports above are unused.

2021-07-28 06:35 UTC, JammingBen approved these changes

2021-07-28 06:55 UTC, jvillafanez commented
Doc ticket opened in https://github.com/owncloud/docs/issues/3901

2021-07-28 19:05 UTC, voroyam commented
```
root@oc:/var/www/owncloud# occ ldap:invalidate-cache carlos


  Too many arguments, expected arguments "command".


ldap:invalidate-cache

root@oc:/var/www/owncloud# occ ldap:invalidate-cache --help
Description:
  invalidates the cache for given users or all users.

Usage:
  ldap:invalidate-cache

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
root@oc:/var/www/owncloud# occ ldap:invalidate-cache
 4/4 [============================] 100%root@oc:/var/www/owncloud#
```

2021-07-28 19:06 UTC, voroyam commented
Command works:

```
root@oc:/var/www/owncloud# occ user:list-groups carlos
  - g2
  - g1
root@oc:/var/www/owncloud# occ group:list-members g1
  - carlos: carlos
  - oc1: oc1 oc1
 ```

```
root@oc:/var/www/owncloud# occ ldap:invalidate-cache
 4/4 [============================] 100%
```

```
root@oc:/var/www/owncloud# occ group:list-members g1
  - oc1: oc1 oc1
  - oc2: oc2 oc2
root@oc:/var/www/owncloud# occ user:list-groups carlos
  - g2
 ```

2021-07-29 10:55 UTC, merged

2021-08-25 09:35 UTC, erwinpalma commented
I have one question about the patch that solves this issue,

This patch will be present in the oc 10.8? os the customer need to patch it after the oc upgrade?

2021-08-25 12:41 UTC, mmattel commented
If an updated LDAP version will be published on the marketplace, we need to add that command also at least to 10.8. A docs issue has been created: https://github.com/owncloud/docs/issues/3901. Please add a note in the dos issue  regarding the plans.

2021-08-30 09:20 UTC, jvillafanez commented
It isn't bound to any particular OC version, so you need whatever minimum version the user_ldap app currently requires (I think it's 10.4)

2021-08-30 09:23 UTC, erwinpalma commented
OK, @jvillafanez,

So, if the customer has oc10.8 then does he need to apply the patch anyway?

2021-08-30 10:03 UTC, jvillafanez commented
Once the new version of the user_ldap app is released, he can install that version.
A patch for the app might work (not tested), but I'd recommend to wait / push for the new app version.

2022-02-07 09:01 UTC, enbrnz commented
Is there also an API endpoint? Then you could configure a trigger on the LDAP backend for changes in the groups available in ownCloud to call that API endpoint.

2022-02-07 10:16 UTC, jvillafanez commented
> Is there also an API endpoint?

Not planned as far as I'm aware of.
I don't know if it's easy or not to setup that feature in the LDAP backend, or how many providers have that kind of support.

2022-02-07 13:35 UTC, enbrnz commented
In Windows AD all you have to do is enable the audit log, then you can just run `attach task to this event.`